# Generated by Django 4.2.9 on 2024-09-09 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_newspaper_publishers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='publishers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
